import Head from 'next/head'
import React from 'react'
import styles from '../styles/Home.module.css'
import Home from './Home'

export default function Index() {
  return (
    <div>
        <Head>
          <title>Form Duo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <React.Fragment>
          <Home/>
      </React.Fragment>
    </div>
  )
}
