import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Index from './Home'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Form Duo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Index/>
    </div>
  )
}
